export const EVENT_BUS = {
  CHECKOUT_SLIDE_RIGHT: 'EVENT_BUS_CHECKOUT_SLIDE_RIGHT',
  CHECKOUT_SLIDE_LEFT: 'EVENT_BUS_CHECKOUT_SLIDE_LEFT',
  CHECK_OUT_PREV: 'EVENT_BUS_CHECK_OUT_PREV',
  CHECK_OUT_NEXT: 'EVENT_BUS_CHECK_OUT_NEXT',
  SCROLL_TOP: 'EVENT_BUS_SCROLL_TOP'
}
