export const PRODUCT = '/products'
export const COLOR = '/colors'
export const SIZE = '/sizes'
export const COLLECTION = '/collections'
export const PRODUCT_DETAIL = '/products/{slug}'
export const CUSTOMCAT_PRODUCT = '/products/create-custom-cat'
export const GET_CUSTOMCAT_PRODUCT = '/products-custom-cat'
